weatherservice:
  key: ${KEY:key}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:${SPRING_DB_URL:postgresql://localhost:5432/java}
    username: ${SPRING_DB_USER:postgres}
    password: ${SPRING_DB_PASSWORD:123@}
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /
